version: '3'
services:
  web-server:
    container_name: web-server
    build: ./app
    ports:
      - 8000:8000
    command: gunicorn --workers=5 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 main:app
    volumes:
      - ./app:/app
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      INFLUXDB_V2_URL: "http://influxdb:8086"
      INFLUXDB_V2_ORG: "aston"
      INFLUXDB_V2_TOKEN: "2UVwEBfD4Kj5FrN5WJHyxcDvw73EfL5RV1IpGE4zv14rIR2RAY-jMFkopjk1_iamFfcwwsHHND2R1Bn4-9mQSA=="
    links:
      - redis
  celery-worker:
    container_name: celery-worker
    build: ./app
    command: celery -A tasks worker --loglevel=INFO
    volumes:
      - ./app:/app
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      ZEPHYR_USERNAME: "AstonUniversity"
      ZEPHYR_PASSWORD: "Xo08R83d43e0Kk6"
      SC_USERNAME: "190102421@aston.ac.uk"
      SC_PASSWORD: "RiyadtheWizard"
      PLUME_EMAIL: "180086320@aston.ac.uk"
      PLUME_PASSWORD: "aston1234"
      INFLUXDB_V2_URL: "http://influxdb:8086"
      INFLUXDB_V2_ORG: "aston"
      INFLUXDB_V2_TOKEN: "2UVwEBfD4Kj5FrN5WJHyxcDvw73EfL5RV1IpGE4zv14rIR2RAY-jMFkopjk1_iamFfcwwsHHND2R1Bn4-9mQSA=="
    links:
      - web-server
      - redis
  # celery flower to monitor celery tasks
  flower:
    image: mher/flower
    command: [ "celery", "flower", "--basic_auth=aston:aston1234" ]
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      FLOWER_PORT: "8888"
      FLOWER_HOST: "0.0.0.0"
    ports:
      - 8888:8888
  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 6379:6379
  # local instance of influx db for testing environment
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
  # Use the influx cli to set up an influxdb instance.
  influxdb_cli:
    links:
      - influxdb
    image: influxdb
    entrypoint: influx setup --bucket plume -t 2UVwEBfD4Kj5FrN5WJHyxcDvw73EfL5RV1IpGE4zv14rIR2RAY-jMFkopjk1_iamFfcwwsHHND2R1Bn4-9mQSA== -o aston --username=aston --password=aston1234 --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on:
      - influxdb




