version: '3'
services:
  web-server:
    container_name: web-server
    build: ./app
    ports:
      - "8000:8000"
    command: gunicorn --workers=3 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 main:app
    volumes:
      - ./app:/usr/src/app
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      INFLUXDB_V2_URL: "${INFLUXDB_V2_URL}"
      INFLUXDB_V2_ORG: "${INFLUXDB_V2_ORG}"
      INFLUXDB_V2_TOKEN: "${INFLUXDB_V2_TOKEN}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_PORT: "${DATABASE_PORT}"
      PLUME_EMAIL: "${PLUME_EMAIL}"
      PLUME_PASSWORD: "${PLUME_PASSWORD}"
    links:
      - redis
  # celery worker process
  celery-worker:
    container_name: celery-worker
    build: ./app
    command: celery -A tasks worker --loglevel=INFO
    volumes:
      - ./app:/usr/src/app
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      ZEPHYR_USERNAME: "${ZEPHYR_USERNAME}"
      ZEPHYR_PASSWORD: "${ZEPHYR_PASSWORD}"
      SC_USERNAME: "${SC_USERNAME}"
      SC_PASSWORD: "${SC_PASSWORD}"
      PLUME_EMAIL: "${PLUME_EMAIL}"
      PLUME_PASSWORD: "${PLUME_PASSWORD}"
      INFLUXDB_V2_URL: "${INFLUXDB_V2_URL}"
      INFLUXDB_V2_ORG: "${INFLUXDB_V2_ORG}"
      INFLUXDB_V2_TOKEN: "${INFLUXDB_V2_TOKEN}"
    links:
      - web-server
      - redis
  # celery beat process separate to workers
  celery-beat:
    container_name: celery-beat
    build: ./app
    command: celery -A tasks beat --loglevel=INFO
    volumes:
      - ./app:/app
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      ZEPHYR_USERNAME: "${ZEPHYR_USERNAME}"
      ZEPHYR_PASSWORD: "${ZEPHYR_PASSWORD}"
      SC_USERNAME: "${SC_USERNAME}"
      SC_PASSWORD: "${SC_PASSWORD}"
      PLUME_EMAIL: "${PLUME_EMAIL}"
      PLUME_PASSWORD: "${PLUME_PASSWORD}"
      INFLUXDB_V2_URL: "${INFLUXDB_V2_URL}"
      INFLUXDB_V2_ORG: "${INFLUXDB_V2_ORG}"
      INFLUXDB_V2_TOKEN: "${INFLUXDB_V2_TOKEN}"
    links:
      - web-server
      - redis
  # celery flower to monitor celery tasks, username = FLOWER_USERNAME, password = FLOWER_PASSWORD
  flower:
    image: mher/flower
    command: [ "celery", "flower", "--basic_auth=${FLOWER_USERNAME}:${FLOWER_PASSWORD}" ]
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      FLOWER_PORT: "8888"
      FLOWER_HOST: "0.0.0.0"
    ports:
      - "8888:8888"
  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - "6379:6379"
