name: Deploy to digital ocean

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old deployment
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd AirQualitySensors && docker-compose down && docker system prune --all --force && cd .. && rm -rf AirQualitySensors
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}

      - name: Deploy new release
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: git clone https://github.com/AstonAirQuality/AirQualitySensors.git && cd AirQualitySensors && docker-compose --env-file ../secrets/env.prod up -d
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
