name: Deploy to digital ocean

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy-on-droplet
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: > 
          docker compose down
          docker system prune --all --force
          git clone https://github.com/AstonAirQuality/AirQualitySensors.git
          cd AirQualitySensors/main
          docker compose up -d
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
